framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: mixlink_app

        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            cache.api_responses:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%/2'
                default_lifetime: 900 # 15 minutes
