knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            redirect_route: app_auth_callback
            redirect_params:
                provider: google
        spotify:
            type: spotify
            client_id: '%env(SPOTIFY_CLIENT_ID)%'
            client_secret: '%env(SPOTIFY_CLIENT_SECRET)%'
            redirect_route: app_auth_callback
            redirect_params:
                provider: spotify
        soundcloud:
            type: generic
            provider_class: League\OAuth2\Client\Provider\GenericProvider
            client_id: '%env(SOUNDCLOUD_CLIENT_ID)%'
            client_secret: '%env(SOUNDCLOUD_CLIENT_SECRET)%'
            redirect_route: app_auth_callback
            redirect_params:
                provider: soundcloud
            provider_options:
                urlAuthorize: 'https://soundcloud.com/connect'
                urlAccessToken: 'https://api.soundcloud.com/oauth2/token'
                urlResourceOwnerDetails: 'https://api.soundcloud.com/me'
                verify: true
