version: 2
enable-beta-ecosystems: true

updates:
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "BaptisteLegat"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      dependencies:
        patterns:
          - "*"
        dependency-type: "production"
      dev-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint*"
          - "eslint-plugin-*"

  - package-ecosystem: "composer"
    directory: "/back"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "BaptisteLegat"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      all-composer:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/front"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    assignees:
      - "BaptisteLegat"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    groups:
      docker-front:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/back"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    assignees:
      - "BaptisteLegat"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    groups:
      docker-back:
        patterns:
          - "*"
