version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "BaptisteLegat"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "composer"
    directory: "/back"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "BaptisteLegat"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    assignees:
      - "BaptisteLegat"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
