version: '3.8'

services:
  php:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: symfony_php
    ports:
      - "8000:8000"
    volumes:
      - ./back:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: symfony_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mixlink
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: vue_front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  db_data:
