services:
  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "80:80"
    volumes:
      - ./back:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  php:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: symfony_php
    restart: always
    volumes:
      - ./.git:/var/www/html/.git
      - ./back:/var/www/html:cached
      - ./back/public:/var/www/html/public
      - ./back/var:/var/www/html/var
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: symfony_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mixlink
      MYSQL_USER: mixlink
      MYSQL_PASSWORD: password
    volumes:
      - ./back/docker/mysql/init/:/docker-entrypoint-initdb.d
      - ./back/docker/mysql/data/:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: vue_front
    ports:
      - "3000:3000"
    volumes:
      - ./front/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
