# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    frontend_url: '%env(FRONTEND_URL)%'
    stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'
    stripePrices:
        free: '%env(STRIPE_PRICE_FREE)%'
        premium: '%env(STRIPE_PRICE_PREMIUM)%'
    stripeWebhookSecret: '%env(STRIPE_WEBHOOK_SECRET)%'
    stripe.secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe.webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'
    mercurePublisherJwtKey: '%env(MERCURE_PUBLISHER_JWT_KEY)%'
    mercurePublicUrl: '%env(MERCURE_PUBLIC_URL)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    gedmo.mapping.driver.attribute:
        class: Gedmo\Mapping\Driver\AttributeReader

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_listener, event: 'onFlush' }
            - { name: doctrine.event_listener, event: 'loadClassMetadata' }
        calls:
            - [ setAnnotationReader, [ "@gedmo.mapping.driver.attribute" ] ]

    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%stripeSecretKey%'
            $stripePrices: '%stripePrices%'
            $stripeWebhookSecret: '%stripe.webhook_secret%'

    App\Mercure\MercureManager:
        arguments:
            $jwtKey: '%mercurePublisherJwtKey%'
            $mercureUrl: '%mercurePublicUrl%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
