name: CI/CD Pipeline

on:
  pull_request:
    branches: [ "*" ]
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']

permissions:
  contents: read

name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mixlink_test
          MYSQL_USER: mixlink
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Compose
        run: docker-compose up -d --build

      - name: Install PHP dependencies
        run: |
          docker exec symfony_php composer install --no-interaction --prefer-dist

      - name: Run database migrations
        run: |
          docker exec symfony_php php bin/console doctrine:migrations:migrate --no-interaction

      - name: Install Node.js dependencies
        run: |
          docker exec vue_front npm install

      - name: Run unit and functional tests
        run: |
          docker exec symfony_php vendor/bin/phpunit

      - name: Shutdown Docker Compose
        if: always()
        run: docker-compose down
